# Generated by Django 2.0.5 on 2018-05-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuserprofile',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
