# Generated by Django 2.0.5 on 2018-05-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180515_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuserprofile',
            name='profile_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('employer', 'Employer')], default='employee', max_length=8),
        ),
    ]
