# Generated by Django 2.0.5 on 2018-05-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180515_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuserprofile',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
