# Generated by Django 2.0.5 on 2018-05-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20180516_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(default='http://placehold.it/200x200', upload_to='media'),
        ),
    ]
