# Generated by Django 2.0.5 on 2018-05-25 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0008_auto_20180525_0900'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', tinymce.models.HTMLField(verbose_name='Content')),
                ('validity_in_months', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('post_as_guest', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('jobposting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_matching', to='company.CompanyProfile')),
                ('jobpostinguser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_matching', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobapply',
            name='job_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobApplications.JobPostingModel'),
        ),
    ]
