# Generated by Django 2.0.5 on 2018-05-25 10:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobApplications', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapply',
            unique_together={('employee', 'job_app')},
        ),
    ]
