# Generated by Django 2.0.5 on 2018-05-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApplications', '0002_auto_20180525_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='status',
            field=models.CharField(choices=[('initated', 'Initiated'), ('no_response', 'no_response'), ('process', 'Process'), ('reject', 'Rejected'), ('hired', 'Hired')], default='initated', max_length=8),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='update_comment',
            field=models.TextField(default='PLease initaite the recruiting process!'),
        ),
    ]
