# Generated by Django 2.0.5 on 2018-05-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='college_name',
            field=models.TextField(default='Please enter college name'),
            preserve_default=False,
        ),
    ]
