# Generated by Django 2.0.5 on 2018-05-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20180516_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicemployeeprofile',
            old_name='age',
            new_name='date_of_birth',
        ),
    ]
