# Generated by Django 2.0.5 on 2018-05-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20180516_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicemployeeprofile',
            name='date_of_birth',
        ),
    ]
