# Generated by Django 2.0.5 on 2018-05-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employeeeducationdetails_grade_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='board',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='degree',
            field=models.CharField(choices=[('Secondary School', 'Secondary School'), ('Higher Secondary', 'Higher Secondary'), ('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation')], default='Secondary School', max_length=100),
        ),
    ]
