# Generated by Django 2.0.5 on 2018-05-17 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180516_0713'),
        ('employee', '0009_auto_20180517_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfessionalDetails',
            fields=[
                ('employeeprofessional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('previous_compnay_name', models.CharField(max_length=255)),
                ('date_of_joining', models.DateField()),
                ('date_of_leaving', models.DateField()),
                ('notice_period_in_months', models.DecimalField(decimal_places=0, max_digits=3)),
                ('current_ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_ctc', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
