# Generated by Django 2.0.5 on 2018-05-18 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employeeprofessionaldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofessionaldetails',
            name='current_ctc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeeprofessionaldetails',
            name='date_of_joining',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='employeeprofessionaldetails',
            name='date_of_leaving',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='employeeprofessionaldetails',
            name='expected_ctc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeeprofessionaldetails',
            name='notice_period_in_months',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
