# Generated by Django 2.0.5 on 2018-05-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20180518_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicemployeeprofile',
            name='picture',
            field=models.ImageField(default='http://placehold.it/200x200', upload_to='media'),
        ),
    ]
