# Generated by Django 2.0.5 on 2018-05-18 11:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import employee.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180516_0713'),
        ('employee', '0013_auto_20180518_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReusmeDetails',
            fields=[
                ('employeeresumedetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('upload_resume', models.FileField(upload_to='media', validators=[employee.validators.validate_file_extension])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 5, 18, 11, 11, 57, 872571, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeeducationdetails',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetails',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetails',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='basicemployeeprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
